# .github/workflows/deploy.yml
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      # Grant specific write permissions required for GitHub Pages deployment
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web App
        # Ensure --base-href matches your GitHub Pages URL structure
        run: flutter build web --release --base-href /preview/

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/web' # The directory containing your built web app

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Official GitHub Pages deployment action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages # Or your chosen publishing branch