# .github/workflows/deploy.yml
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch, e.g., 'master'
  workflow_dispatch: # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Use v4 for better compatibility

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Specify your Flutter version, e.g., '3.22.x' or 'stable'
          channel: 'stable'

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release --base-href /preview/ # IMPORTANT: Replace YOUR_REPOSITORY_NAME with your actual GitHub repository name

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # A popular action for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub Actions
          publish_dir: ./build/web # Directory containing your built web app
          publish_branch: gh-pages # The branch where your web app will be published (GitHub Pages default)
          user_name: 'github-actions[bot]' # Optional: Sets the commit author for the deployment
          user_email: 'github-actions[bot]@users.noreply.github.com' # Optional: Sets the commit email